odom_frame: odom
base_frame: base_link
map_frame: map

map_update_interval: 2.0  # Publish new map (seconds)
throttle_scans: 1  # 1 = no scans skipped

maxRange: 12.0 # Max sensor value
maxUrange: 12.0 # Usable region of the sensor
particles: 100

# minimumScore: 40

# Update frequencies
linearUpdate: 0.05
angularUpdate: 0.02
temporalUpdate: 0.02
# resampleThreshold: 0.7

srr: 0.05
srt: 0.05
str: 0.05
stt: 0.05

# Initial Map Size
xmin: -15.0
ymin: -15.0
xmax: 15.0
ymax: 15.0
delta: 0.05

# All default
# sigma: 0.01
# kernelSize: 1
# lstep: 0.01
# astep: 0.01
# iterations: 8
# lsigma: 0.075
# ogain: 3.0
# lskip: 0
# llsamplerange: 0.01
# llsamplestep: 0.01
# lasamplerange: 0.005
# lasamplestep: 0.005
minimumScore: 50
