scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.35
    upper_threshold: 12.0
# - name: angle
#   type: laser_filters/LaserScanAngularBoundsFilterInPlace
#   params:
#     lower_angle: -2.35619
#     upper_angle: -1.57079
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_tilt_link
    min_x: -0.23
    max_x: 0.23
    min_y: -0.23
    max_y: 0.23
    min_z: 0.0
    max_z: 0.2
