base_link_to_camera_tilt:
  parent: base_tilt_link
  child: camera_tilt_link
  translate: [0.1983, 0.0, 0.229]
  rotate: [0, 0, 0, 1]

camera_armature_to_link:
  parent: camera_armature_link
  child: camera_link
  translate: [0.0, 0.0, 0.0]
  rotate: [0, 0, 0, 1]
base_tilt_link_to_laser:
  parent: base_tilt_link
  child: laser
  translate: [-0.0553, 0.116, 0.253]
  rotate: [0, 0, 1, 0]
base_tilt_link_to_imu:
  parent: base_tilt_link
  child: imu
  translate: [0.0634, 0.0012, 0.2039]
  rotate: [0.0000, 0.0000, 0.7071, 0.7071]

base_link_to_footprint:
  parent: base_link
  child: base_tilt_link
  translate: [0.0, 0.0, 0.0]
  rotate: [0, 0, 0, 1]
camera_tilt_to_armature:
  parent: camera_tilt_link
  child: camera_armature_link
  translate: [0.0, 0.0, 0.0]
  rotate: [0, 0, 0, 1]
