#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

mkdir -p ${HOME}/tj2_ros/logs
mkdir -p ${HOME}/tj2_ros/bags

cd ${BASE_DIR}/resources

docker run -it \
    --name workstation_build_tj2_ros \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v /home/${USER}/tj2_ros:/root/tj2_ros:rw \
    -v /home/${USER}/tj2_ros/workstation/docker/resources/scripts:/root/scripts:rw \
    --rm \
    tj2_ros_workstation:latest \
    /root/install/build_tj2_ros.sh
