#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

TJ2_ROS_BASE=${BASE_DIR}/../..

${BASE_DIR}/copy_tj2_ros

cd ${BASE_DIR}/resources

${BASE_DIR}/stop_main_container

IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)

if [ "${IMAGE_PREFIX}" == "workstation" ]; then
    BUILD_FLAGS='-DCATKIN_BLACKLIST_PACKAGES=tj2_yolo'
else
    # TODO: add cxx11 ABI library to docker
    BUILD_FLAGS='-DCATKIN_BLACKLIST_PACKAGES=tj2_yolo'
    # BUILD_FLAGS=-DCATKIN_BLACKLIST_PACKAGES=\'\'
fi

docker run -it \
    --user tj2 \
    --name workstation_build_tj2_ros \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=tj2_ros_workstation_build:/home/tj2/ros_ws:rw \
    -v=${TJ2_ROS_BASE}:/home/tj2/tj2_ros:rw \
    -v=${TJ2_ROS_BASE}/scripts:/home/tj2/scripts:rw \
    --rm \
    tj2_ros_${IMAGE_PREFIX}:latest \
    /home/tj2/scripts/build_tj2_ros.sh ${BUILD_FLAGS} -DARCHITECTURE=x86_64
