#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

TJ2_ROS_BASE=${BASE_DIR}/../..

mkdir -p ${TJ2_ROS_BASE}/logs
mkdir -p ${TJ2_ROS_BASE}/bags

cd ${BASE_DIR}/resources

VALUE=`docker volume ls -f name=tj2_ros_workstation_build`
if ! echo ${VALUE} | grep -q "tj2_ros_workstation_build"; then
    echo "Creating volume"
    docker volume create tj2_ros_workstation_build
fi

docker run -it \
    --name workstation_build_tj2_ros \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=tj2_ros_workstation_build:/root/ros_ws:rw \
    -v=${TJ2_ROS_BASE}:/root/tj2_ros:rw \
    -v=${TJ2_ROS_BASE}/scripts:/root/scripts:rw \
    --rm \
    tj2_ros_workstation:latest \
    /root/install/copy_tj2_ros.sh
