#!/bin/bash
function cleanup {
    xhost -local:root
}
trap cleanup EXIT

DATASET=$1

echo ${DATASET}

xhost +local:root
docker run -it \
    --name label_images \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=/home/${USER}/tj2_ros:/home/tj2:rw \
    -v=/home/${USER}/tj2_ros/workstation/docker/resources/scripts:/home/tj2/scripts:rw \
    -v=/home/${USER}/tj2_ros/workstation/docker/resources/configs/default_config.yaml:/home/tj2/default_config.yaml:rw \
    -v="${DATASET}":/home/tj2/dataset \
    -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --rm \
    tj2_ros_workstation:latest \
    /entrypoint.sh labelme /home/tj2/dataset --labels /home/tj2/dataset/labels.txt --config /home/tj2/default_config.yaml
