#!/bin/bash
if [ -z $1 ]; then
    BASE_DIR=$(realpath "$(dirname $0)")
else
    BASE_DIR=$(realpath "$1")
fi

cd ${BASE_DIR}/../../.devcontainer
docker-compose -f docker-compose.gpu.yaml -f docker-compose.yaml up -d
