#!/bin/bash
function cleanup {
    xhost -local:root
}
trap cleanup EXIT

HOST_MACHINE=$1
CONFIG_FILE=${2:-standard.rviz}

xhost +local:root
docker run -it \
    --name workstation_rviz \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="HOST_MACHINE=$HOST_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=/home/${USER}/tj2_ros:/root:rw \
    -v=/home/${USER}/tj2_ros/workstation/docker/resources/scripts:/root/scripts:rw \
    -v="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --rm \
    tj2_ros_workstation:latest \
    /entrypoint.sh rviz -d /root/ros_ws/src/tj2_ros/tj2_viz/rviz/${CONFIG_FILE}
