# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
      {id: 1, size: 0.1524, name: tag1},
      {id: 2, size: 0.1524, name: tag2},
      {id: 3, size: 0.1524, name: tag3},
      {id: 4, size: 0.1524, name: tag4},
      {id: 5, size: 0.1524, name: tag5},
      {id: 6, size: 0.1524, name: tag6},
      {id: 7, size: 0.1524, name: tag7},
      {id: 8, size: 0.1524, name: tag8},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'field',
      layout:
      [
        {id: 1, size: 0.1524, x: -7.243096, y:  2.936589, z:  0.467500, qx:  0.5000, qy:  0.5000, qz:  0.5000, qw:  0.5000},  # red alliance community, POV robot: right-most, POV field: (+X, +Y)
        {id: 2, size: 0.1524, x: -7.243096, y:  1.260189, z:  0.467500, qx:  0.5000, qy:  0.5000, qz:  0.5000, qw:  0.5000},  # red alliance community, POV robot: center, POV field: (+X, +Y)
        {id: 3, size: 0.1524, x: -7.243096, y: -0.416211, z:  0.467500, qx:  0.5000, qy:  0.5000, qz:  0.5000, qw:  0.5000},  # red alliance community, POV robot: left-most, POV field: (+X, +Y)
        {id: 4, size: 0.1524, x: -7.908322, y: -2.741613, z:  0.467500, qx:  0.5000, qy:  0.5000, qz:  0.5000, qw:  0.5000},  # red alliance substation, POV field: (+X, -Y)
        {id: 5, size: 0.1524, x:  7.908322, y: -2.741613, z:  0.467500, qx: -0.5000, qy:  0.5000, qz:  0.5000, qw: -0.5000},  # blue alliance substation, POV field: (-X, -Y)
        {id: 6, size: 0.1524, x:  7.243096, y: -0.416211, z:  0.467500, qx: -0.5000, qy:  0.5000, qz:  0.5000, qw: -0.5000},  # blue alliance community, POV robot: right-most, POV field: (-X, +Y)
        {id: 7, size: 0.1524, x:  7.243096, y:  1.260189, z:  0.467500, qx: -0.5000, qy:  0.5000, qz:  0.5000, qw: -0.5000},  # blue alliance community, POV robot: center, POV field: (-X, +Y)
        {id: 8, size: 0.1524, x:  7.243096, y:  2.936589, z:  0.467500, qx: -0.5000, qy:  0.5000, qz:  0.5000, qw: -0.5000},  # blue alliance community, POV robot: left-most, POV field: (-X, +Y)
      ]
    }
  ]

#     CHARGED UP 2023 FIELD
#         SCORING TABLE
#   RED                   BLUE
# |----------------------------|
# |-- 1                   8 -- |
# |              +Y            |
# |-- 2          |        7 -- |
# |              o--+X         |
# |-- 3                   6 -- |
# |                            |
# |-4                        5-|
# |----------------------------|
