meas_std_val: 0.1
u_std: [0.008, 0.008, 0.008]
initial_range: [0.25, 0.25, 1.0]
num_particles: 50
initial_distribution_type: "gaussian"
loop_rate: 15.0
stale_detection_seconds: 1.0
particle_filter_type: "ParticleFilter"
tag_id_to_waypoint_map: {
  "1": "tag1"
}
robot_frame: "base_link"
global_frame: "map"
publish_tf: true
debug: true
