meas_std_val: 0.1
u_std: [0.01, 0.01, 0.01]
initial_range: [1.0, 1.0, 6.14]
num_particles: 50
initial_distribution_type: "gaussian"
loop_rate: 15.0
stale_detection_seconds: 1.0
particle_filter_type: "ParticleFilter"
tag_id_to_waypoint_map: {
  "1": "tag1"
}
robot_frame: "base_link"
global_frame: "map"
publish_tf: true
debug: true
