#!/bin/bash
if [ -z $1 ]; then
    BASE_DIR=$(realpath "$(dirname $0)")
else
    BASE_DIR=$(realpath "$1")
fi

export TJ2_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.roscore.yml -f docker-compose.tj2_ros.yml up -d
