version: "3"

volumes:
  tj2_ros_workstation_build:
    name: tj2_ros_workstation_build
    external: true

services:
  tj2_ros_workstation:
    image: tj2_ros_workstation:latest
    container_name: tj2_ros_workstation
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    ports: [ "9090:9090", "10000:10000" ]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    # Share IPC with the host: enables us to request X to draw things, see
    # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
    ipc: host
    volumes:
      - tj2_ros_workstation_build:/home/tj2/ros_ws:rw
      - /home/${USER}/tj2_ros:/home/tj2/tj2_ros:rw
      - /home/${USER}/tj2_ros/workstation/docker/resources/scripts:/home/tj2/scripts:rw
      - /home/${USER}/tj2_ros/logs:/home/tj2/logs:rw
      - /home/${USER}/tj2_ros/bags:/home/tj2/bags:rw
    command: [ "/launch.sh" ]
