scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.15
    upper_threshold: .inf
- name: chassis_obstruction_1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.0
    upper_angle: 2.077219
- name: chassis_obstruction_2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 6.28319
    upper_angle: 4.20
- name: pillar_obstruction
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 2.162480
    upper_angle: 2.499101

# scan_filter_chain:
# - name: range_filter
#   type: laser_filters/LaserScanRangeFilter
#   params:
#     lower_threshold: 0.7
#     upper_threshold: .inf
