scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.15
    upper_threshold: .inf
- name: chassis_obstruction_1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.0
    upper_angle: 0.30
- name: chassis_obstruction_2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 5.98242
    upper_angle: 6.28319
- name: pillar_obstruction
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 3.784084
    upper_angle: 4.120705

# scan_filter_chain:
# - name: range_filter
#   type: laser_filters/LaserScanRangeFilter
#   params:
#     lower_threshold: 0.7
#     upper_threshold: .inf