version: "3"

volumes:
  workstation_tj2_ros_build:
    name: workstation_tj2_ros_build
    external: true

services:
  tj2_ros_devcontainer:
    image: workstation_${TJ2_IMAGE_VERSION}
    container_name: tj2_ros_devcontainer
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    ports: [ "9090:9090", "10000:10000" ]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    # Share IPC with the host: enables us to request X to draw things, see
    # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
    ipc: host
    volumes:
      - workstation_tj2_ros_build:/home/tj2/ros_ws:rw
      - /home/${USER}/tj2_ros:/opt/tj2/tj2_ros:rw
      - /home/${USER}/tj2_ros/scripts:/opt/tj2/scripts:rw
      - /media/storage/training_tj2_ros_data:/opt/tj2/tj2_ros/dataset_builder/data:rw
      - /home/${USER}/tj2_ros/logs:/opt/tj2/logs:rw
      - /media/storage/tj2_ros_bags/bags/:/opt/tj2/bags:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/opt/tj2/.docker:rw # docker looks here inside a container
      - /var/run/docker.sock:/var/run/docker.sock

    command: bash /opt/tj2/scripts/watch_for_changes.sh
