version: "3"

volumes:
  tj2_ros_workstation_build:
    name: tj2_ros_workstation_build
    external: true

services:
  tj2_ros_training:
    image: tj2_ros_training:latest
    container_name: tj2_ros_training
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    ports: [ "9090:9090", "10000:10000" ]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    # Share IPC with the host: enables us to request X to draw things, see
    # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
    ipc: host
    volumes:
      - tj2_ros_workstation_build:/home/tj2/ros_ws:rw
      - /home/${USER}/tj2_ros:/home/tj2/tj2_ros:rw
      - /home/${USER}/tj2_ros/src:/home/tj2/ros_ws/src/tj2_ros:rw
      - /home/${USER}/tj2_ros/workstation/docker/resources/scripts:/home/tj2/scripts:rw
      - /media/storage/tj2_ros_training_data:/home/tj2/tj2_ros/dataset_builder/data:rw
      - /home/${USER}/tj2_ros/logs:/home/tj2/logs:rw
      - /media/storage/tj2_ros_bags/bags/:/home/tj2/bags:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/home/tj2/.docker:rw # docker looks here inside a container
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "sleep infinity"
