#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

cd ${BASE_DIR}/../../scripts
./prioritize_wifi.sh

export TJ2_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.roscore.yml -f docker-compose.tj2_ros.yml stop
docker build -f ./Dockerfile -t $(${BASE_DIR}/../get_image_tag) .
