#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

cd ${BASE_DIR}/../resources

docker-compose -f docker-compose.tj2_ros.yml stop
docker run \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v /home/${USER}/tj2_ros:/root/tj2_ros:rw \
    -v /home/${USER}/tj2_ros/scripts:/root/scripts:rw \
    --rm \
    --gpus all \
    tj2_ros:latest \
    /root/install/build_tj2_ros.sh
