#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

VALUE=`docker volume ls -f name=tj2_ros_build`
if ! echo ${VALUE} | grep -q "tj2_ros_build"; then
    echo "Creating volume"
    docker volume create tj2_ros_build
fi

TJ2_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
docker run \
    --user tj2 \
    --name build_tj2_ros \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=tj2_ros_build:/home/tj2/ros_ws:rw \
    -v=/home/${USER}/tj2_ros:/home/tj2/tj2_ros:rw \
    -v=/home/${USER}/tj2_ros/scripts:/home/tj2/scripts:rw \
    --rm \
    ${TJ2_IMAGE_VERSION} \
    /home/tj2/scripts/copy_tj2_ros.sh
