#!/bin/bash
set -e

docker images
echo "Paste in image ID to push: "
read TAG_IMAGE_ID
docker tag ${TAG_IMAGE_ID} woz4tetra/tj2_ros:latest
docker push woz4tetra/tj2_ros:latest

cd /media/storage
if [ -f tj2_ros_ws.tar.gz ]; then
    echo "$pwd/tj2_ros_ws.tar.gz exists. Remove it to create a new one."
else
    echo "Compressing docker_ros_ws"
    tar -cvf tj2_ros_ws.tar.gz docker_ros_ws
fi
echo "Done!"
