#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

mkdir -p ~/docker_ros_ws/src
mkdir -p ~/docker_ros_ws/devel
touch ~/docker_ros_ws/devel/setup.bash

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.roscore.yml -f docker-compose.tj2_ros.yml stop

echo "Running post build"

docker run \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v /home/${USER}/docker_ros_ws:/root/ros_ws:rw \
    -v /home/${USER}/tj2_ros/src:/root/ros_ws/src/tj2_ros:rw \
    -v /home/${USER}/tj2_ros/scripts:/root/scripts:rw \
    --rm \
    --gpus all \
    tj2_ros:latest \
    /root/install/post_build.sh $@

echo "Post build complete"
