#!/bin/bash

function cleanup {
    xhost -local:root
}
trap cleanup EXIT

xhost +local:root

docker exec -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    tj2_ros_devcontainer \
    env TERM=xterm-256color \
    /opt/tj2/entrypoint.sh /bin/bash
