#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

REMOTE_MACHINE=$1
JOYSTICK_DEVICE=$2

TJ2_ROS_BASE=${BASE_DIR}/../..
TJ2_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
IMAGE_PREFIX=workstation

docker run -it \
    --name workstation_joystick \
    --env="REMOTE_MACHINE=$REMOTE_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=workstation_tj2_ros_build:/home/tj2/ros_ws:rw \
    -v=${TJ2_ROS_BASE}:/opt/tj2/tj2_ros:rw \
    -v=${TJ2_ROS_BASE}/scripts:/opt/tj2/scripts:rw \
    --rm \
    ${IMAGE_PREFIX}_${TJ2_IMAGE_VERSION} \
    /opt/tj2/entrypoint.sh roslaunch tj2_debug_joystick remote_joystick.launch device:=$JOYSTICK_DEVICE
