#!/bin/bash
if [ -z $1 ]; then
    BASE_DIR=$(realpath "$(dirname $0)")
else
    BASE_DIR=$(realpath "$1")
fi

IMAGE_PREFIX=$(${BASE_DIR}/get_built_image)

cd ${BASE_DIR}/../resources
docker-compose -f docker-compose.${IMAGE_PREFIX}_tj2_ros.yml stop
