- left_outer_climber_joint
- left_inner_climber_joint
- right_outer_climber_joint
- right_inner_climber_joint
- left_outer_climber_hook_joint
- left_inner_climber_hook_joint
- right_outer_climber_hook_joint
- right_inner_climber_hook_joint
- intake_joint
- turret_joint
- camera_joint
