version: "3"

services:
  tj2_ros:
    image: tj2_ros:latest
    container_name: tj2_ros
    restart: "no"
    network_mode: "host"
    runtime: "nvidia"
    privileged: true
    stop_signal: SIGINT
    environment:
      - ROS_MASTER_INTERFACE=eth0
    group_add:
      - dialout
    volumes:
      - /home/${USER}/tj2_ros:/root/tj2_ros:rw
      - /home/${USER}/tj2_ros/scripts:/root/scripts:rw
      - /home/${USER}/tj2_ros/docker/resources/configs/zed:/usr/local/zed/settings/:rw
      - /media/storage:/media/storage:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      # Allow container to control NetworkManager
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    command: [ "/launch.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
