version: "3"

services:
  roscore:
    image: tj2_ros:latest
    container_name: roscore
    restart: "no"
    network_mode: "host"
    environment:
      - ROS_MASTER_INTERFACE=eth0
    volumes:
      - /home/${USER}/tj2_ros/scripts:/root/scripts:rw
    privileged: true
    entrypoint: ["/roscore.sh"]
    stop_signal: SIGTERM

