version: "3"

volumes:
    workstation_tj2_ros_build:
        name: workstation_tj2_ros_build
        external: true

services:
    workstation_tj2_ros:
        image: ${TJ2_IMAGE_VERSION}
        container_name: workstation_tj2_ros
        restart: "no"
        network_mode: "host"
        privileged: true
        stop_signal: SIGINT
        ports: ["9090:9090", "10000:10000"]
        environment:
            - DISPLAY=${DISPLAY}
            - XAUTHORITY=${XAUTHORITY}
            - IMAGE_VERSION=${TJ2_IMAGE_VERSION}
        # Share IPC with the host: enables us to request X to draw things, see
        # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
        ipc: host
        volumes:
            - workstation_tj2_ros_build:/home/tj2/ros_ws:rw
            - /home/${USER}/tj2_ros:/opt/tj2/tj2_ros:rw
            - /home/${USER}/tj2_ros/workstation/docker/resources/scripts:/opt/tj2/scripts:rw
            - /home/${USER}/tj2_ros/logs:/opt/tj2/logs:rw
            - /home/${USER}/tj2_ros/bags:/opt/tj2/bags:rw
        command: ["/opt/tj2/launch.sh"]
