version: "3"

services:
  post_build:
    image: tj2_ros:latest
    container_name: post_build
    restart: "no"
    network_mode: "host"
    runtime: "nvidia"
    privileged: true
    group_add:
      - dialout
    volumes:
      - /home/${USER}/docker_ros_ws:/root/ros_ws:rw
      - /home/${USER}/tj2_ros/src:/root/ros_ws/src/tj2_ros:rw
      - /home/${USER}/tj2_ros/scripts:/root/scripts:rw
      - /run/systemd:/run/systemd:rw
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/root/.docker:rw # docker looks here inside a container
      - /home/${USER}/.docker:/home/${USER}/.docker:rw # but we need to satisfy spice-lib.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "/root/install/post_build.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
