- base_link_to_wheel_0_joint
- base_link_to_wheel_1_joint
- base_link_to_wheel_2_joint
- base_link_to_wheel_3_joint
- arm1_base_to_arm1_link
- arm2_base_to_arm2_link
- arm3_base_to_arm3_link
- end_effector_base_to_end_effector_link
- intake_base_to_intake_link
