scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.35
    upper_threshold: .inf
# - name: angle
#   type: laser_filters/LaserScanAngularBoundsFilterInPlace
#   params:
#     lower_angle: -1.570796
#     upper_angle: 1.570796
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_tilt_link
    min_x: -0.428625
    max_x: 0.428625
    min_y: -0.428625
    max_y: 0.428625
    min_z: 0.0
    max_z: 0.2
