start_service_name: "start_capture" # Defines name suffix for std_srvs::Empty service which restarts suspended streaming
stop_service_name: "stop_capture"   # Defines name suffix for std_srvs::Empty service which suspends camera polling timer

video_device: /dev/v4l/by-path/platform-3610000.xhci-usb-0:2.3:1.0-video-index0           # Device driver's entrypoint
io_method: mmap                     # I/O method
                                    # - read - for devices supporting virtual filesystem or block I/O
                                    # - mmap - for devices with direct libusb memory mapping
                                    # - userptr - for userspace devices supporting userspace pointer exchange
pixel_format: mjpeg                    # Pixel format for Video4linux device (also selects decoder mode)
                                        # https://wiki.videolan.org/YUV#YUV_4:2:0_.28I420.2FJ420.2FYV12.29
                                        # - yuyv - YUV420
                                        # - yuv - synonym for yuyv
                                        # - uyvy - UVY240
                                        # - yuvmono10 - Monochrome 10-bit pseudo-YUV
                                        # - rgb24 - Linear 8-bit RGB
                                        # - bgr24 - OpenCV-compatible 8-bit BGR
                                        # - grey - Grayscale 8-bit monochrome
                                        # - yu12 - YU-reversed YUV420
                                        # - mjpeg - FFMPEG decoder, MotionJPEG, for compatible hardware
                                        # - h264 - FFMPEG decoder, H.264, for compatible hardware
color_format: yuv422p               # On-chip color representation mode for the input frame encoded by hardware
                                        # - yuv422p - YUV422 - default, compatible with most MJPEG hardware encoders
                                        # - yuv420p - YUV420 - mandatory for H.264 and H.265 hardware encoders
create_suspended: false             # Instructs the node whether to start streaming immediately after launch
                                    # or to wait until the start service will be triggered
full_ffmpeg_log: false              # Allows to suppress warning messages generated by libavcodec, cleans log
camera_name: camera_0            # ROS internal name for the camera, used to generate camera_info message
camera_frame_id: camera_0        # Frame ID used to generate coordinate transformations
camera_transport_suffix: image_raw  # Suffix used by image_transport to generate topic names
camera_info_url: ""                 # URI for camera calibration data (likely a YML file obtained from camera_calibration)
image_width: 1600                    # Frame dimensions, should be supported by camera hardware
image_height: 1200
framerate: 50                       # Camera polling frequency, Hz (integer)

autoexposure: false
exposure: 25
gain: 5
auto_white_balance: false
white_balance: 4600
